spring:
  datasource:
    url: jdbc:mysql://mysql-order:3306/order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:order_user}
    password: ${DB_PASSWORD:order_pass}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
